In [4]:
import pandas as pd
import numpy as np

print("Python is working!")

Python is working!

In [ ]:
%pip install pandas numpy

In [ ]:
df = pd.read_csv("../data/airline_passenger_satisfaction.csv")

In [22]:
#checking the shape of the dataset
df.shape

(129880, 24)

In [23]:
#preview of the first 5 passenger records
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [24]:
#checking for data types and missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ID                                      129880 non-null  int64
 1   Gender                                  129880 non-null  str
 2   Age                                     129880 non-null  int64
 3   Customer Type                           129880 non-null  str
 4   Type of Travel                          129880 non-null  str
 5   Class                                   129880 non-null  str
 6   Flight Distance                         129880 non-null  int64
 7   Departure Delay                         129880 non-null  int64
 8   Arrival Delay                           129487 non-null  float64
 9   Departure and Arrival Time Convenience  129880 non-null  int64
 10  Ease of Online Booking                  129880 non-null  int64
 11  Check-in Service                        129880 non-null  int64
 12  Online Boarding                         129880 non-null  int64
 13  Gate Location                           129880 non-null  int64
 14  On-board Service                        129880 non-null  int64
 15  Seat Comfort                            129880 non-null  int64
 16  Leg Room Service                        129880 non-null  int64
 17  Cleanliness                             129880 non-null  int64
 18  Food and Drink                          129880 non-null  int64
 19  In-flight Service                       129880 non-null  int64
 20  In-flight Wifi Service                  129880 non-null  int64
 21  In-flight Entertainment                 129880 non-null  int64
 22  Baggage Handling                        129880 non-null  int64
 23  Satisfaction                            129880 non-null  str
dtypes: float64(1), int64(18), str(5)
memory usage: 23.8 MB

In [25]:
#checks for missing values in each column
df.isnull().sum()

ID                                          0
Gender                                      0
Age                                         0
Customer Type                               0
Type of Travel                              0
Class                                       0
Flight Distance                             0
Departure Delay                             0
Arrival Delay                             393
Departure and Arrival Time Convenience      0
Ease of Online Booking                      0
Check-in Service                            0
Online Boarding                             0
Gate Location                               0
On-board Service                            0
Seat Comfort                                0
Leg Room Service                            0
Cleanliness                                 0
Food and Drink                              0
In-flight Service                           0
In-flight Wifi Service                      0
In-flight Entertainment                     0
Baggage Handling                            0
Satisfaction                                0
dtype: int64

In [ ]:
#checks for duplicate passenger records (identical rows)
df.duplicated().sum()

np.int64(0)

In [ ]:
#checks for duplicate IDs
df["ID"].duplicated().sum()

np.int64(0)

In [ ]:
#shows each unique value for each catergorical data variable
print("Gender:")
print(df["Gender"].unique())

print("\nCustomer Type:")
print(df["Customer Type"].unique())

print("\nType of Travel:")
print(df["Type of Travel"].unique())

print("\nClass:")
print(df["Class"].unique())

print("\nSatisfaction:")
print(df["Satisfaction"].unique())

Gender:
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Customer Type:
<StringArray>
['First-time', 'Returning']
Length: 2, dtype: str

Type of Travel:
<StringArray>
['Business', 'Personal']
Length: 2, dtype: str

Class:
<StringArray>
['Business', 'Economy', 'Economy Plus']
Length: 3, dtype: str

Satisfaction:
<StringArray>
['Neutral or Dissatisfied', 'Satisfied']
Length: 2, dtype: str

In [10]:
#shows the range for numerical variable's ratings
rating_columns = [
    "Departure and Arrival Time Convenience",
    "Ease of Online Booking",
    "Check-in Service",
    "Online Boarding",
    "Gate Location",
    "On-board Service",
    "Seat Comfort",
    "Leg Room Service",
    "Cleanliness",
    "Food and Drink",
    "In-flight Service",
    "In-flight Wifi Service",
    "In-flight Entertainment",
    "Baggage Handling"
]

df[rating_columns].nunique()

Departure and Arrival Time Convenience    6
Ease of Online Booking                    6
Check-in Service                          6
Online Boarding                           6
Gate Location                             6
On-board Service                          6
Seat Comfort                              6
Leg Room Service                          6
Cleanliness                               6
Food and Drink                            6
In-flight Service                         6
In-flight Wifi Service                    6
In-flight Entertainment                   6
Baggage Handling                          5
dtype: int64

In [ ]:
#counts how many passengers have a 0 (N/A rating) for each variable
rating_columns = [
    "Departure and Arrival Time Convenience",
    "Ease of Online Booking",
    "Check-in Service",
    "Online Boarding",
    "Gate Location",
    "On-board Service",
    "Seat Comfort",
    "Leg Room Service",
    "Cleanliness",
    "Food and Drink",
    "In-flight Service",
    "In-flight Wifi Service",
    "In-flight Entertainment",
    "Baggage Handling"
]

zero_counts = (df[rating_columns] == 0).sum()

zero_counts

Departure and Arrival Time Convenience    6681
Ease of Online Booking                    5682
Check-in Service                             1
Online Boarding                           3080
Gate Location                                1
On-board Service                             5
Seat Comfort                                 1
Leg Room Service                           598
Cleanliness                                 14
Food and Drink                             132
In-flight Service                            5
In-flight Wifi Service                    3916
In-flight Entertainment                     18
Baggage Handling                             0
dtype: int64

In [26]:
#percentage of how many passengers have a 0 (N/A rating) for each variable
zero_percentages = ((df[rating_columns] == 0).mean() * 100).round(2)

zero_percentages

Departure and Arrival Time Convenience    5.14
Ease of Online Booking                    4.37
Check-in Service                          0.00
Online Boarding                           2.37
Gate Location                             0.00
On-board Service                          0.00
Seat Comfort                              0.00
Leg Room Service                          0.46
Cleanliness                               0.01
Food and Drink                            0.10
In-flight Service                         0.00
In-flight Wifi Service                    3.02
In-flight Entertainment                   0.01
Baggage Handling                          0.00
dtype: float64

In [11]:
#checks for ratings outside the 0-5 range
for column in rating_columns:
    print(column, sorted(df[column].unique()))

Departure and Arrival Time Convenience [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Ease of Online Booking [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Check-in Service [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Online Boarding [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Gate Location [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
On-board Service [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Seat Comfort [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Leg Room Service [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Cleanliness [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Food and Drink [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
In-flight Service [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
In-flight Wifi Service [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
In-flight Entertainment [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Baggage Handling [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [12]:
#creates a new cleaned dataset replacing 0's with NaN
df_clean = df.copy()

df_clean[rating_columns] = df_clean[rating_columns].replace(0, np.nan)

#making sure count of NaN is the same as the previous 0's
df_clean[rating_columns].isnull().sum()

Departure and Arrival Time Convenience    6681
Ease of Online Booking                    5682
Check-in Service                             1
Online Boarding                           3080
Gate Location                                1
On-board Service                             5
Seat Comfort                                 1
Leg Room Service                           598
Cleanliness                                 14
Food and Drink                             132
In-flight Service                            5
In-flight Wifi Service                    3916
In-flight Entertainment                     18
Baggage Handling                             0
dtype: int64

In [13]:
#checks for missing data in the new cleaned dataset
#there is more now because we changed 0's to NaN
#Arrival Delay has actual missing data (same as before)
df_clean.isnull().sum()

ID                                           0
Gender                                       0
Age                                          0
Customer Type                                0
Type of Travel                               0
Class                                        0
Flight Distance                              0
Departure Delay                              0
Arrival Delay                              393
Departure and Arrival Time Convenience    6681
Ease of Online Booking                    5682
Check-in Service                             1
Online Boarding                           3080
Gate Location                                1
On-board Service                             5
Seat Comfort                                 1
Leg Room Service                           598
Cleanliness                                 14
Food and Drink                             132
In-flight Service                            5
In-flight Wifi Service                    3916
In-flight Entertainment                     18
Baggage Handling                             0
Satisfaction                                 0
dtype: int64

In [14]:
#making sure none of the data got removed after cleaning
df_clean.shape

(129880, 24)

In [32]:
#checking how many passengers are satisfied vs. neutral/dissatisfied
df_clean["Satisfaction"].value_counts()

#turns it into a percentage
df_clean["Satisfaction"].value_counts(normalize=True) * 100

Satisfaction
Neutral or Dissatisfied    56.553742
Satisfied                  43.446258
Name: proportion, dtype: float64

In [33]:
#checking if first-time and returning passengers have different satisfaction rates

pd.crosstab(
    df_clean["Customer Type"],
    df_clean["Satisfaction"],
    normalize="index"
) * 100

Satisfaction   Neutral or Dissatisfied  Satisfied
Customer Type
First-time                   76.030278  23.969722
Returning                    52.188501  47.811499

In [34]:
#checking if business vs. personal travel have different satisfaction rates
pd.crosstab(
    df_clean["Type of Travel"],
    df_clean["Satisfaction"],
    normalize="index"
) * 100

Satisfaction    Neutral or Dissatisfied  Satisfied
Type of Travel
Business                      41.627552  58.372448
Personal                      89.867370  10.132630

In [ ]:
#checking if business, economy, and economy plus classes have different satisfaction rates
pd.crosstab(
    df_clean["Class"],
    df_clean["Satisfaction"],
    normalize="index"
) * 100

Satisfaction  Neutral or Dissatisfied  Satisfied
Class
Business                    30.556628  69.443372
Economy                     81.232743  18.767257
Economy Plus                75.358623  24.641377

In [37]:
#seeing if travel purpose and cabin class are connected
pd.crosstab(
    df_clean["Type of Travel"],
    df_clean["Class"],
    normalize="index"
) * 100

Class            Business    Economy  Economy Plus
Type of Travel
Business        66.322901  28.211789      5.465309
Personal         6.651405  82.128549     11.220046

In [15]:
'''
seeing if within each cabin class, does travel purpose still correspond
to different satisfaction levels?
'''
pd.crosstab(
    [df_clean["Type of Travel"], df_clean["Class"]],
    df_clean["Satisfaction"],
    normalize="index"
) * 100

Satisfaction                 Neutral or Dissatisfied  Satisfied
Type of Travel Class
Business       Business                    27.962412  72.037588
               Economy                     70.052166  29.947834
               Economy Plus                60.730314  39.269686
Personal       Business                    88.290311  11.709689
               Economy                     89.804575  10.195425
               Economy Plus                91.261921   8.738079

In [ ]:
'''
seeing for first-time vs. returning passengers what
percentage travel for business or personal travel
'''
pd.crosstab(
    df_clean["Customer Type"],
    df_clean["Type of Travel"],
    normalize="index"
) * 100

Type of Travel   Business   Personal
Customer Type
First-time      99.154752   0.845248
Returning       62.312912  37.687088

In [ ]:
#presents a table showing the average of each passenger's experience factor
df_clean.groupby("Satisfaction")[rating_columns].mean().T

Satisfaction                            Neutral or Dissatisfied  Satisfied
Departure and Arrival Time Convenience                 3.285290   3.142030
Ease of Online Booking                                 2.617090   3.244406
Check-in Service                                       3.043008   3.649004
Online Boarding                                        2.708061   4.153870
Gate Location                                          2.980055   2.972903
On-board Service                                       3.019742   3.856171
Seat Comfort                                           3.038039   3.966417
Leg Room Service                                       3.006488   3.834051
Cleanliness                                            2.933359   3.746509
Food and Drink                                         2.961526   3.528888
In-flight Service                                      3.389832   3.970990
In-flight Wifi Service                                 2.398750   3.393511
In-flight Entertainment                                2.893142   3.964202
Baggage Handling                                       3.374912   3.966914

In [28]:
#calculate the difference gap in satisfied and neutral/dissatisfied 
satisfaction_gaps = (
    df_clean.groupby("Satisfaction")[rating_columns]
    .mean()
    .T
)

satisfaction_gaps["Difference"] = (
    satisfaction_gaps["Satisfied"]
    - satisfaction_gaps["Neutral or Dissatisfied"]
)

satisfaction_gaps = satisfaction_gaps.sort_values(
    "Difference",
    ascending=False
)

satisfaction_gaps

Satisfaction,Neutral or Dissatisfied,Satisfied,Difference
Online Boarding,2.708061,4.153870,1.445809
In-flight Entertainment,2.893142,3.964202,1.071060
In-flight Wifi Service,2.398750,3.393511,0.994761
Seat Comfort,3.038039,3.966417,0.928378
On-board Service,3.019742,3.856171,0.836429
Leg Room Service,3.006488,3.834051,0.827563
Cleanliness,2.933359,3.746509,0.813150
Ease of Online Booking,2.617090,3.244406,0.627316
Check-in Service,3.043008,3.649004,0.605996
Baggage Handling,3.374912,3.966914,0.592002
In-flight Service,3.389832,3.970990,0.581157
Food and Drink,2.961526,3.528888,0.567362
Gate Location,2.980055,2.972903,-0.007152
Departure and Arrival Time Convenience,3.285290,3.142030,-0.143259

In [29]:
#average service ratings for business vs. personal travelers
travel_satisfaction = (
    df_clean.groupby(["Type of Travel", "Satisfaction"])[rating_columns]
    .mean()
    .T
)

travel_satisfaction

Type of Travel                                        Business            \
Satisfaction                           Neutral or Dissatisfied Satisfied
Departure and Arrival Time Convenience                2.823727  3.093198
Ease of Online Booking                                2.761530  3.171942
Check-in Service                                      2.760285  3.672091
Online Boarding                                       2.619201  4.154601
Gate Location                                         3.036130  2.978550
On-board Service                                      2.778796  3.902437
Seat Comfort                                          2.893481  4.025346
Leg Room Service                                      2.934892  3.863359
Cleanliness                                           2.751467  3.795955
Food and Drink                                        2.859701  3.560274
In-flight Service                                     3.186757  3.999045
In-flight Wifi Service                                2.401747  3.320353
In-flight Entertainment                               2.736033  4.036577
Baggage Handling                                      3.182420  3.997479

Type of Travel                                        Personal
Satisfaction                           Neutral or Dissatisfied Satisfied
Departure and Arrival Time Convenience                3.742795  3.746918
Ease of Online Booking                                2.463803  4.362246
Check-in Service                                      3.335290  3.352161
Online Boarding                                       2.801968  4.143023
Gate Location                                         2.922082  2.900295
On-board Service                                      3.268808  3.261297
Seat Comfort                                          3.187484  3.208743
Leg Room Service                                      3.080946  3.437144
Cleanliness                                           3.121335  3.110756
Food and Drink                                        3.066844  3.123828
In-flight Service                                     3.599751  3.610265
In-flight Wifi Service                                2.395653  4.496480
In-flight Entertainment                               3.055489  3.033644
Baggage Handling                                      3.573917  3.573919

In [ ]:
#calculate the difference gaps for only business travelers
business_gaps = (
    df_clean[df_clean["Type of Travel"] == "Business"]
    .groupby("Satisfaction")[rating_columns]
    .mean()
    .T
)

business_gaps["Difference"] = (
    business_gaps["Satisfied"]
    - business_gaps["Neutral or Dissatisfied"]
)

business_gaps.sort_values("Difference", ascending=False)

Satisfaction,Neutral or Dissatisfied,Satisfied,Difference
Online Boarding,2.619201,4.154601,1.535401
In-flight Entertainment,2.736033,4.036577,1.300544
Seat Comfort,2.893481,4.025346,1.131865
On-board Service,2.778796,3.902437,1.123641
Cleanliness,2.751467,3.795955,1.044488
Leg Room Service,2.934892,3.863359,0.928466
In-flight Wifi Service,2.401747,3.320353,0.918607
Check-in Service,2.760285,3.672091,0.911806
Baggage Handling,3.182420,3.997479,0.815059
In-flight Service,3.186757,3.999045,0.812288
Food and Drink,2.859701,3.560274,0.700574
Ease of Online Booking,2.761530,3.171942,0.410412
Departure and Arrival Time Convenience,2.823727,3.093198,0.269472
Gate Location,3.036130,2.978550,-0.057580

In [32]:
#calculate the difference gap for only personal travelers
personal_gaps = (
    df_clean[df_clean["Type of Travel"] == "Personal"]
    .groupby("Satisfaction")[rating_columns]
    .mean()
    .T
)

personal_gaps["Difference"] = (
    personal_gaps["Satisfied"]
    - personal_gaps["Neutral or Dissatisfied"]
)

personal_gaps.sort_values("Difference", ascending=False)

Satisfaction,Neutral or Dissatisfied,Satisfied,Difference
In-flight Wifi Service,2.395653,4.496480,2.100827
Ease of Online Booking,2.463803,4.362246,1.898443
Online Boarding,2.801968,4.143023,1.341055
Leg Room Service,3.080946,3.437144,0.356198
Food and Drink,3.066844,3.123828,0.056984
Seat Comfort,3.187484,3.208743,0.021258
Check-in Service,3.335290,3.352161,0.016871
In-flight Service,3.599751,3.610265,0.010514
Departure and Arrival Time Convenience,3.742795,3.746918,0.004124
Baggage Handling,3.573917,3.573919,0.000003
On-board Service,3.268808,3.261297,-0.007511
Cleanliness,3.121335,3.110756,-0.010578
Gate Location,2.922082,2.900295,-0.021788
In-flight Entertainment,3.055489,3.033644,-0.021845

In [ ]:
#create departure delay categories
#On time / early: ≤ 0 minutes
#Minor delay: 1–15 minutes
#Moderate delay: 16–60 minutes
#Major delay: 61+ minutes
df_clean["Departure Delay Category"] = pd.cut(
    df_clean["Departure Delay"],
    bins=[-float("inf"), 0, 15, 60, float("inf")],
    labels=["On Time / Early", "Minor Delay", "Moderate Delay", "Major Delay"]
)

In [ ]:
#percentage of passengers in each depature delay category
#who were satisfied vs. neutral/dissatisfied
pd.crosstab(
    df_clean["Departure Delay Category"],
    df_clean["Satisfaction"],
    normalize="index"
) * 100

Satisfaction              Neutral or Dissatisfied  Satisfied
Departure Delay Category
On Time / Early                         54.061018  45.938982
Minor Delay                             56.454457  43.545543
Moderate Delay                          62.498735  37.501265
Major Delay                             64.144847  35.855153

In [35]:
#arrival delay categories
#same as above
df_clean["Arrival Delay Category"] = pd.cut(
    df_clean["Arrival Delay"],
    bins=[-float("inf"), 0, 15, 60, float("inf")],
    labels=["On Time / Early", "Minor Delay", "Moderate Delay", "Major Delay"]
)

In [38]:
#percentage of passengers in each arrival delay category
#who were satisfied vs. neutral/dissatisfied
pd.crosstab(
    df_clean["Arrival Delay Category"],
    df_clean["Satisfaction"],
    normalize="index"
) * 100

Satisfaction            Neutral or Dissatisfied  Satisfied
Arrival Delay Category
On Time / Early                       52.593020  47.406980
Minor Delay                           58.809243  41.190757
Moderate Delay                        64.118222  35.881778
Major Delay                           64.425616  35.574384

In [39]:
#determines how many passengers have complete rating information
cluster_data = df_clean[rating_columns].copy()

print("Total passengers:", len(cluster_data))
print("Passengers with complete ratings:", len(cluster_data.dropna()))
print(
    "Percent with complete ratings:",
    round(len(cluster_data.dropna()) / len(cluster_data) * 100, 2),
    "%"
)

Total passengers: 129880
Passengers with complete ratings: 119567
Percent with complete ratings: 92.06 %

In [40]:
#create clustering dataset
cluster_data = df_clean[rating_columns].dropna().copy()

cluster_data.shape

(119567, 14)

In [41]:
#average and spread of each rating
cluster_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Departure and Arrival Time Convenience,119567.0,3.206838,1.386886,1.0,2.0,3.0,4.0,5.0
Ease of Online Booking,119567.0,2.879172,1.298754,1.0,2.0,3.0,4.0,5.0
Check-in Service,119567.0,3.294747,1.266249,1.0,2.0,3.0,4.0,5.0
Online Boarding,119567.0,3.330551,1.263108,1.0,2.0,4.0,4.0,5.0
Gate Location,119567.0,2.986961,1.282049,1.0,2.0,3.0,4.0,5.0
On-board Service,119567.0,3.386185,1.285412,1.0,2.0,4.0,4.0,5.0
Seat Comfort,119567.0,3.456221,1.311765,1.0,2.0,4.0,5.0,5.0
Leg Room Service,119567.0,3.380381,1.295580,1.0,2.0,4.0,4.0,5.0
Cleanliness,119567.0,3.294053,1.310393,1.0,2.0,3.0,4.0,5.0
Food and Drink,119567.0,3.213788,1.324438,1.0,2.0,3.0,4.0,5.0
In-flight Service,119567.0,3.646399,1.165786,1.0,3.0,4.0,5.0,5.0
In-flight Wifi Service,119567.0,2.817943,1.253511,1.0,2.0,3.0,4.0,5.0
In-flight Entertainment,119567.0,3.380423,1.327173,1.0,2.0,4.0,4.0,5.0
Baggage Handling,119567.0,3.637333,1.167878,1.0,3.0,4.0,5.0,5.0

In [ ]:
%pip install scikit-learn
from sklearn.preprocessing import StandardScaler

Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/60/ea/57e57539ce175d774fc291ed091b0a6d756854b92cd92554c6bb4d0ae498/scikit_learn-1.9.1-cp312-cp312-macosx_12_0_arm64.whl.metadata
  Downloading scikit_learn-1.9.1-cp312-cp312-macosx_12_0_arm64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn) (2.5.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Obtaining dependency information for scipy>=1.10.0 from https://files.pythonhosted.org/packages/a5/f6/a5b82f8abbe14d134691b8b903696f701d25a081353a29dc655c364d9e62/scipy-1.18.1-cp312-cp312-macosx_14_0_arm64.whl.metadata
  Downloading scipy-1.18.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 2.9 MB/s eta 0:00:00
Collecting joblib>=1.4.0 (from scikit-learn)
  Obtaining dependency information for joblib>=1.4.0 from https://files.pythonhosted.org/packages/18/53/84099323c2ec4be98d935f63c033ac4151ee83836ca1050ede3b3aadf155/joblib-1.6.0-py3-none-any.whl.metadata
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Obtaining dependency information for narwhals>=2.0.1 from https://files.pythonhosted.org/packages/40/b5/1b84b2c784db76d69442334bc8b8748c840f13ca53be086f4f250ad4a0bc/narwhals-2.26.0-py3-none-any.whl.metadata
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=3.5.0 from https://files.pythonhosted.org/packages/43/3f/f88a53f60a472b46f4023f56d204dd7de33d34c5d2acbfa0d70a674e639e/threadpoolctl-3.7.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Obtaining dependency information for cloudpickle>=3.0 from https://files.pythonhosted.org/packages/88/39/799be3f2f0f38cc727ee3b4f1445fe6d5e4133064ec2e4115069418a5bb6/cloudpickle-3.1.2-py3-none-any.whl.metadata
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp312-cp312-macosx_12_0_arm64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 42.3 MB/s eta 0:00:0000:0100:01
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 306.1/306.1 kB 23.0 MB/s eta 0:00:00
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.0/474.0 kB 28.6 MB/s eta 0:00:00
Downloading scipy-1.18.1-cp312-cp312-macosx_14_0_arm64.whl (20.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.5/20.5 MB 42.5 MB/s eta 0:00:0000:0100:01
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.26.0 scikit-learn-1.9.1 scipy-1.18.1 threadpoolctl-3.7.0

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: pip3.12 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [44]:
#standardizing the variables
scaler = StandardScaler()

cluster_scaled = scaler.fit_transform(cluster_data)

cluster_scaled.shape

(119567, 14)

In [ ]:
#using elbow method to test several values of k (number of clusters)
#and measures how tightly passengers fit within each cluster
from sklearn.cluster import KMeans

inertia = []

k_values = range(2, 9)

for k in k_values:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    
    kmeans.fit(cluster_scaled)
    inertia.append(kmeans.inertia_)

list(zip(k_values, inertia))

[(2, 1343958.2743784331),
 (3, 1194041.8133730888),
 (4, 1085601.771283614),
 (5, 1033958.6130467181),
 (6, 986684.165071263),
 (7, 946178.0897015489),
 (8, 914994.4151104216)]

In [ ]:
#graphs it
%pip install matplotlib
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))

plt.plot(k_values, inertia, marker="o")

plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.title("Elbow Method for K-Means Clustering")

plt.show()

In [48]:
#building the 4 cluster model
kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

cluster_labels = kmeans.fit_predict(cluster_scaled)

In [50]:
#sees how many passengers end up in each cluster
pd.Series(cluster_labels).value_counts().sort_index()

0    29159
1    33346
2    27772
3    29290
Name: count, dtype: int64

In [51]:
#attach each passenger's cluster number back to the clustering dataset
cluster_profiles = cluster_data.copy()

cluster_profiles["Cluster"] = cluster_labels

In [52]:
#calculates the average rating for every service within each cluster
cluster_means = cluster_profiles.groupby("Cluster").mean()

cluster_means.T

Cluster                                        0         1         2         3
Departure and Arrival Time Convenience  4.282794  2.455137  3.282695  2.919563
Ease of Online Booking                  4.194177  2.067114  2.636720  2.724445
Check-in Service                        3.625124  3.728123  3.009362  2.743052
Online Boarding                         4.109366  3.563966  2.305488  3.261420
Gate Location                           4.014712  2.163318  2.999208  2.889894
On-board Service                        3.944065  4.112187  3.204523  2.176511
Seat Comfort                            4.028259  4.181581  1.847760  3.586036
Leg Room Service                        3.874104  3.895160  3.244383  2.431751
Cleanliness                             3.866251  4.036046  1.717485  3.374531
Food and Drink                          3.698515  3.813771  1.746327  3.439570
In-flight Service                       4.137282  4.288940  3.684466  2.390099
In-flight Wifi Service                  4.216400  2.163828  2.357086  2.607409
In-flight Entertainment                 4.150451  4.355215  1.943864  2.866166
Baggage Handling                        4.120100  4.267618  3.666571  2.411437

In [ ]:
#add the cluster labels
clustered_passengers = df_clean.loc[cluster_data.index].copy()

clustered_passengers["Cluster"] = cluster_labels

clustered_passengers.shape

(119567, 27)

In [54]:
#checking satisfaction by cluster
pd.crosstab(
    clustered_passengers["Cluster"],
    clustered_passengers["Satisfaction"],
    normalize="index"
) * 100

Satisfaction  Neutral or Dissatisfied  Satisfied
Cluster
0                           26.681299  73.318701
1                           38.289450  61.710550
2                           88.650439  11.349561
3                           79.784910  20.215090

In [55]:
#checks all passengers in each cluster on percentage of
#business travelers vs personal travelers
pd.crosstab(
    clustered_passengers["Cluster"],
    clustered_passengers["Type of Travel"],
    normalize="index"
) * 100

Type of Travel   Business   Personal
Cluster
0               78.901883  21.098117
1               75.688238  24.311762
2               55.069855  44.930145
3               65.332878  34.667122

In [56]:
#checks all passengers in each cluster on percentage of
#first time or returning customers
pd.crosstab(
    clustered_passengers["Cluster"],
    clustered_passengers["Customer Type"],
    normalize="index"
) * 100

Customer Type  First-time  Returning
Cluster
0               12.023732  87.976268
1               11.731542  88.268458
2               26.692352  73.307648
3               15.032434  84.967566

In [57]:
#checks all passengers in each cluster on percentage of
#business, economy, and economy plus
pd.crosstab(
    clustered_passengers["Cluster"],
    clustered_passengers["Class"],
    normalize="index"
) * 100

Class     Business    Economy  Economy Plus
Cluster
0        62.172914  31.900957      5.926129
1        65.360163  29.862652      4.777185
2        26.346680  63.582025     10.071295
3        37.268692  53.646296      9.085012

In [58]:
#create prediction target
#turns satisfied into 1 and neutral/dissatisfied into 0
df_model = df_clean.copy()

df_model["Satisfied"] = (
    df_model["Satisfaction"] == "Satisfied"
).astype(int)

df_model[["Satisfaction", "Satisfied"]].head(10)

              Satisfaction  Satisfied
0  Neutral or Dissatisfied          0
1                Satisfied          1
2                Satisfied          1
3                Satisfied          1
4                Satisfied          1
5                Satisfied          1
6                Satisfied          1
7                Satisfied          1
8  Neutral or Dissatisfied          0
9                Satisfied          1

In [59]:
#creating the first predictive model
model_features = [
    "Gender",
    "Age",
    "Customer Type",
    "Type of Travel",
    "Class",
    "Flight Distance",
    "Departure Delay",
    "Arrival Delay"
] + rating_columns

X = df_model[model_features].copy()
y = df_model["Satisfied"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (129880, 22)
y shape: (129880,)

In [60]:
#seperating numeric and categorical variables
numeric_features = [
    "Age",
    "Flight Distance",
    "Departure Delay",
    "Arrival Delay"
] + rating_columns

categorical_features = [
    "Gender",
    "Customer Type",
    "Type of Travel",
    "Class"
]

print("Numeric features:", len(numeric_features))
print("Categorical features:", len(categorical_features))

Numeric features: 18
Categorical features: 4

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [69]:
#preprocessor
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(
            handle_unknown="ignore",
            drop="first"
        ))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [71]:
#splitting the data, using 80% to train the model
#and 20% holds back to test it
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training passengers:", len(X_train))
print("Testing passengers:", len(X_test))

Training passengers: 103904
Testing passengers: 25976

In [72]:
#training a logistic regression model
from sklearn.linear_model import LogisticRegression

logistic_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", LogisticRegression(max_iter=1000))
    ]
)

logistic_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Flight Distance',
                                                   'Departure Delay',
                                                   'Arrival Delay',
                                                   'Departure and Arrival Time '
                                                   'Convenience',
                                                   'Ease of Online Booking',
                                                   'Check-in Service',
                                                   'Online Boarding',
                                                   'Gate Location',
                                                   'On-board Service',
                                                   'Se...
                                                   'Cleanliness',
                                                   'Food and Drink',
                                                   'In-flight Service',
                                                   'In-flight Wifi Service',
                                                   'In-flight Entertainment',
                                                   'Baggage Handling']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['Gender', 'Customer Type',
                                                   'Type of Travel',
                                                   'Class'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [73]:
from sklearn.metrics import accuracy_score

y_pred = logistic_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")

Accuracy: 89.06 %

In [74]:
#classification report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90     14690
           1       0.87      0.87      0.87     11286

    accuracy                           0.89     25976
   macro avg       0.89      0.89      0.89     25976
weighted avg       0.89      0.89      0.89     25976

In [75]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[13279  1411]
 [ 1431  9855]]

In [77]:
#pulling out all the variable names after preprocessing
feature_names = logistic_model.named_steps[
    "preprocessor"
].get_feature_names_out()

coefficients = logistic_model.named_steps[
    "classifier"
].coef_[0]

feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
})

feature_importance["Absolute Coefficient"] = (
    feature_importance["Coefficient"].abs()
)

feature_importance = feature_importance.sort_values(
    "Absolute Coefficient",
    ascending=False
)

feature_importance.head(15)

,Feature,Coefficient,Absolute Coefficient
20,cat__Type of Travel_Personal,-2.988081,2.988081
19,cat__Customer Type_Returning,2.373404,2.373404
7,num__Online Boarding,1.136763,1.136763
22,cat__Class_Economy Plus,-1.015943,1.015943
15,num__In-flight Wifi Service,1.009526,1.009526
21,cat__Class_Economy,-0.854017,0.854017
6,num__Check-in Service,0.417588,0.417588
9,num__On-board Service,0.401630,0.401630
11,num__Leg Room Service,0.368122,0.368122
4,num__Departure and Arrival Time Convenience,-0.366058,0.366058
3,num__Arrival Delay,-0.318471,0.318471
12,num__Cleanliness,0.298038,0.298038
5,num__Ease of Online Booking,0.249643,0.249643
8,num__Gate Location,-0.242487,0.242487
14,num__In-flight Service,0.154226,0.154226

In [78]:
#calculates ROC-AUC
#measures how well the model distinguishes satisfied passengers
#from neutral/dissatisfied across different classification thresholds
from sklearn.metrics import roc_auc_score

y_prob = logistic_model.predict_proba(X_test)[:, 1]

roc_auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", round(roc_auc, 3))

ROC-AUC: 0.956

In [79]:
#training random forest comparison model
from sklearn.ensemble import RandomForestClassifier

random_forest_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", RandomForestClassifier(
            n_estimators=200,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

random_forest_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Flight Distance',
                                                   'Departure Delay',
                                                   'Arrival Delay',
                                                   'Departure and Arrival Time '
                                                   'Convenience',
                                                   'Ease of Online Booking',
                                                   'Check-in Service',
                                                   'Online Boarding',
                                                   'Gate Location',
                                                   'On-board Service',
                                                   'Se...
                                                   'In-flight Service',
                                                   'In-flight Wifi Service',
                                                   'In-flight Entertainment',
                                                   'Baggage Handling']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['Gender', 'Customer Type',
                                                   'Type of Travel',
                                                   'Class'])])),
                ('classifier',
                 RandomForestClassifier(n_estimators=200, n_jobs=-1,
                                        random_state=42))])

In [80]:
rf_pred = random_forest_model.predict(X_test)
rf_prob = random_forest_model.predict_proba(X_test)[:, 1]

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_auc = roc_auc_score(y_test, rf_prob)

print("Random Forest Accuracy:", round(rf_accuracy * 100, 2), "%")
print("Random Forest ROC-AUC:", round(rf_auc, 3))

Random Forest Accuracy: 95.83 %
Random Forest ROC-AUC: 0.993

In [81]:
#evaluating random forest across both classes
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.96     14690
           1       0.97      0.93      0.95     11286

    accuracy                           0.96     25976
   macro avg       0.96      0.96      0.96     25976
weighted avg       0.96      0.96      0.96     25976

In [82]:
#finding random forest's most important features
rf_feature_names = random_forest_model.named_steps[
    "preprocessor"
].get_feature_names_out()

rf_importances = random_forest_model.named_steps[
    "classifier"
].feature_importances_

rf_feature_importance = pd.DataFrame({
    "Feature": rf_feature_names,
    "Importance": rf_importances
})

rf_feature_importance = rf_feature_importance.sort_values(
    "Importance",
    ascending=False
)

rf_feature_importance.head(15)

                         Feature  Importance
7           num__Online Boarding    0.181090
15   num__In-flight Wifi Service    0.110512
20  cat__Type of Travel_Personal    0.110350
21            cat__Class_Economy    0.078937
16  num__In-flight Entertainment    0.059921
10             num__Seat Comfort    0.056082
1           num__Flight Distance    0.039610
11         num__Leg Room Service    0.038604
0                       num__Age    0.037600
19  cat__Customer Type_Returning    0.034539
9          num__On-board Service    0.030272
5    num__Ease of Online Booking    0.029011
17         num__Baggage Handling    0.027743
12              num__Cleanliness    0.026944
14        num__In-flight Service    0.026900

In [83]:
model_comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "Accuracy": [0.8906, 0.9583],
    "ROC-AUC": [0.956, 0.993],
    "Macro F1": [0.89, 0.96]
})

model_comparison

                 Model  Accuracy  ROC-AUC  Macro F1
0  Logistic Regression    0.8906    0.956      0.89
1        Random Forest    0.9583    0.993      0.96

## Business Recommendations

### 1. Strengthen the Digital Passenger Journey
Online boarding and in-flight Wi-Fi consistently emerged as prominent indicators of passenger satisfaction. The airline should prioritize a streamlined digital boarding experience, reliable onboard connectivity, and simplified online booking, with targeted support for passenger segments experiencing digital friction.

### 2. Personalize Interventions for Economy Passenger Experience Gaps
Customer segmentation revealed that lower-satisfaction Economy passengers experience different types of friction. Some passengers reported weaker comfort and amenity experiences, while others experienced greater service and operational friction. The airline should tailor customer experience improvements to these distinct needs rather than applying the same intervention to all dissatisfied passengers.

### 3. Develop a First-Time Passenger Experience Strategy
First-time passengers had substantially lower satisfaction than returning passengers and were more concentrated in the lowest-satisfaction customer segment. The airline should consider targeted pre-trip guidance, digital onboarding, and post-trip engagement designed to reduce friction for new customers.

### 4. Use Delay Severity to Trigger Proactive Service Recovery
Passenger satisfaction declined as departure and arrival delays became more severe. The airline should use delay severity as a trigger for proactive communication and customer support, such as updated connection information, rebooking assistance, and appropriate service-recovery interventions.

In [84]:
#add in readable cluster names
cluster_names = {
    0: "Seamless Experience",
    1: "Onboard Positive, Digital Friction",
    2: "Comfort & Amenities Friction",
    3: "Service & Operations Friction"
}

clustered_passengers["Customer Segment"] = (
    clustered_passengers["Cluster"].map(cluster_names)
)

clustered_passengers[
    ["Cluster", "Customer Segment"]
].head(10)

   Cluster                    Customer Segment
0        1  Onboard Positive, Digital Friction
1        1  Onboard Positive, Digital Friction
2        0                 Seamless Experience
3        1  Onboard Positive, Digital Friction
4        3       Service & Operations Friction
5        0                 Seamless Experience
6        1  Onboard Positive, Digital Friction
7        0                 Seamless Experience
8        1  Onboard Positive, Digital Friction
9        1  Onboard Positive, Digital Friction

In [85]:
print("Dashboard rows:", clustered_passengers.shape[0])
print("Dashboard columns:", clustered_passengers.shape[1])

clustered_passengers.columns.tolist()

Dashboard rows: 119567
Dashboard columns: 28

['ID',
 'Gender',
 'Age',
 'Customer Type',
 'Type of Travel',
 'Class',
 'Flight Distance',
 'Departure Delay',
 'Arrival Delay',
 'Departure and Arrival Time Convenience',
 'Ease of Online Booking',
 'Check-in Service',
 'Online Boarding',
 'Gate Location',
 'On-board Service',
 'Seat Comfort',
 'Leg Room Service',
 'Cleanliness',
 'Food and Drink',
 'In-flight Service',
 'In-flight Wifi Service',
 'In-flight Entertainment',
 'Baggage Handling',
 'Satisfaction',
 'Departure Delay Category',
 'Arrival Delay Category',
 'Cluster',
 'Customer Segment']

In [ ]:
clustered_passengers.to_csv(
    "../data/airline_customer_dashboard.csv",
    index=False
)

print("Dashboard dataset exported!")

Dashboard dataset exported!

In [88]:
#reformatting the data for tableau
experience_drivers = pd.DataFrame({
    "Experience Attribute": [
        "Online Boarding",
        "In-flight Entertainment",
        "In-flight Wifi Service",
        "Seat Comfort",
        "On-board Service",
        "Leg Room Service",
        "Cleanliness",
        "Ease of Online Booking",
        "Check-in Service",
        "Baggage Handling",
        "In-flight Service",
        "Food and Drink",
        "Gate Location",
        "Departure and Arrival Time Convenience"
    ],
    "Satisfaction Gap": [
        1.445809,
        1.071060,
        0.994761,
        0.928378,
        0.836429,
        0.827563,
        0.813150,
        0.627316,
        0.605996,
        0.592002,
        0.581157,
        0.567362,
        -0.007152,
        -0.143259
    ]
})

experience_drivers.to_csv(
    "../data/experience_drivers.csv",
    index=False
)

experience_drivers

                      Experience Attribute  Satisfaction Gap
0                          Online Boarding          1.445809
1                  In-flight Entertainment          1.071060
2                   In-flight Wifi Service          0.994761
3                             Seat Comfort          0.928378
4                         On-board Service          0.836429
5                         Leg Room Service          0.827563
6                              Cleanliness          0.813150
7                   Ease of Online Booking          0.627316
8                         Check-in Service          0.605996
9                         Baggage Handling          0.592002
10                       In-flight Service          0.581157
11                          Food and Drink          0.567362
12                           Gate Location         -0.007152
13  Departure and Arrival Time Convenience         -0.143259